"""Load the exported CDC catalog YAML into meida's ``series_catalog`` table.

The catalog is what makes series *discoverable*: which ones exist, what facets
pick them out, and which tool fetches them. It is generated by
:mod:`catalog` / :mod:`catalog_timeseries` into ``data/cdc_series_*.yaml``,
which is gitignored regenerable build output that no runtime code reads -- so
until it lands in the database, nothing on the server can enumerate the ~2,500
Socrata series, only fetch one whose facets you already know.

Upsert on ``(source, series_id)``, preserving ``catalog_id`` and
``created_at``, so a re-export after regenerating the catalog replaces rows in
place. Unlike :mod:`load_timeseries` this also *prunes*: the catalog is
rewritten whole on every export, so a series that disappears from it has
genuinely gone away and must not linger as an orphan row promising data the
fetch tools cannot serve.
"""
from __future__ import annotations

from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Iterator

import sqlalchemy as sa
import yaml
from sqlalchemy.dialects.postgresql import insert as pg_insert

from environment import get_meida_db_url

TABLE_NAME = "series_catalog"


def read_catalog(directory: Path, source: str) -> Iterator[dict[str, Any]]:
    """Yield every entry across one source's per-group catalog files."""
    for path in sorted(directory.glob(f"{source}_series_*.yaml")):
        doc = yaml.safe_load(path.read_text())
        for entry in doc.get("series", []):
            yield entry


def _as_date(value: Any) -> date | None:
    """Catalog bounds are ISO after ``normalize_catalog``, bare years before it."""
    if not value:
        return None
    text = str(value).strip()
    try:
        if len(text) == 4:
            return date(int(text), 1, 1)
        return date.fromisoformat(text[:10])
    except ValueError:
        return None


def _retrieval(entry: dict[str, Any]) -> dict[str, Any]:
    """How this series is fetched -- the field that lets one listing serve both routes.

    ``catalog_timeseries`` writes an explicit block for the stored (WONDER and
    NVSR) entries. Socrata entries carry none, so it is derived here from what
    a ``cdc_series_data`` call actually needs: the dataset and the facets.

    Every catalogued series now has a route. The ``tool: None`` fallback stays
    as a guard -- an entry that reaches it is a bug in the generator, not a
    known gap -- and is asserted against in the tests.
    """
    if entry.get("retrieval"):
        return dict(entry["retrieval"])
    if entry.get("dataset_id"):
        return {"tool": "cdc_series_data",
                "dataset_id": entry["dataset_id"],
                "concept": entry.get("concept"),
                "facets": entry.get("facets") or {}}
    return {"tool": None, "note": "multi-query union; no single-call route"}


def _row(entry: dict[str, Any], source: str, now: datetime) -> dict[str, Any]:
    return {
        "source": source,
        "series_id": entry["series_id"],
        "dataset_id": entry.get("dataset_id"),
        "concept": entry.get("concept"),
        "title": entry.get("title") or entry["series_id"],
        "description": entry.get("description"),
        "units": entry.get("units") or entry.get("unit"),
        "frequency": entry.get("frequency"),
        "provisional": bool(entry.get("provisional")),
        "is_active": entry.get("is_active"),
        "facets": entry.get("facets") or {},
        "retrieval": _retrieval(entry),
        "observation_start": _as_date(entry.get("observation_start")),
        "observation_end": _as_date(entry.get("observation_end")),
        "updated_at": now,
    }


def load(
    directory: Path,
    source: str,
    db_url: str | None = None,
    *,
    prune: bool = True,
    now: datetime | None = None,
) -> dict[str, int]:
    """Upsert one source's catalog, returning counts written and removed.

    *source* is both the namespace written to the rows and the scope of the
    prune, so passing the wrong one deletes another source's entries wholesale.
    It also selects the files: ``<source>_series_*.yaml``.
    """
    now = now or datetime.now(timezone.utc)
    rows = [_row(entry, source, now) for entry in read_catalog(directory, source)]
    if not rows:
        raise FileNotFoundError(
            f"no {source}_series_*.yaml under {directory} -- regenerate the catalog first"
        )

    engine = sa.create_engine(db_url or get_meida_db_url())
    table = sa.Table(TABLE_NAME, sa.MetaData(), autoload_with=engine)
    with engine.begin() as conn:
        stmt = pg_insert(table).values(rows)
        conn.execute(stmt.on_conflict_do_update(
            constraint="uq_sc_source_series",
            # catalog_id and created_at are deliberately absent: a re-export
            # must not break references or reset provenance.
            set_={c: stmt.excluded[c] for c in (
                "dataset_id", "concept", "title", "description", "units",
                "frequency", "provisional", "is_active", "facets", "retrieval",
                "observation_start", "observation_end", "updated_at")},
        ))
        removed = 0
        if prune:
            result = conn.execute(sa.delete(table).where(
                table.c.source == source,
                table.c.series_id.notin_([r["series_id"] for r in rows]),
            ))
            removed = result.rowcount or 0
    engine.dispose()
    return {"written": len(rows), "pruned": removed}


if __name__ == "__main__":
    import sys

    print(load(Path(sys.argv[1]), sys.argv[2]))
